--- #YAML:1.0
name:               Text-TabFile
version:            1.13
abstract:           Parsing tab delimited files
author:
    - Phil Pollard <bennie@cpan.org>
license:            artistic_2
distribution_type:  module
configure_requires:  {}
build_requires:  {}
requires:
    perl:             5.006
    Test:             0
    Text::Delimited:  2.00
resources:
    bugtracker:
        web:  https://rt.cpan.org/Dist/Display.html?Name=Text-TabFile
    repository:
        type:  git
        url:   git://github.com/bennie/perl-Text-TabFile.git
        web:   http://github.com/bennie/perl-Text-TabFile
no_index:
    directory:
        - t
        - inc
        - t
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
